Separate darwin syscalls for mmap (#1149)
Using the unix package by default for other systems instead of syscall.

This way when systems get added to unix, they will work without change.
And the special case is restricted only to darwin builds.

I encountered problems building on Solaris prior to this patch:
github.com/dgraph-io/badger/y/mmap_unix.go:57:30: undefined: syscall.SYS_MADVISE
But unix.Madvise works fine on that platform (and others).